/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DPNToken } from "./DPNToken";
export type { NodeRegistry } from "./NodeRegistry";
export type { NodeRightsNFT } from "./NodeRightsNFT";
export type { Participation } from "./Participation";
export type { StakingPool } from "./StakingPool";
