/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace NodeRightsNFT {
  export type NodeRightsStruct = {
    nodeType: BigNumberish;
    stakedETH: BigNumberish;
    stakedDPN: BigNumberish;
    mintedAt: BigNumberish;
    lastRewardClaim: BigNumberish;
    status: BigNumberish;
    totalUptime: BigNumberish;
    performanceScore: BigNumberish;
    metadata: string;
    isUpgraded: boolean;
  };

  export type NodeRightsStructOutput = [
    nodeType: bigint,
    stakedETH: bigint,
    stakedDPN: bigint,
    mintedAt: bigint,
    lastRewardClaim: bigint,
    status: bigint,
    totalUptime: bigint,
    performanceScore: bigint,
    metadata: string,
    isUpgraded: boolean
  ] & {
    nodeType: bigint;
    stakedETH: bigint;
    stakedDPN: bigint;
    mintedAt: bigint;
    lastRewardClaim: bigint;
    status: bigint;
    totalUptime: bigint;
    performanceScore: bigint;
    metadata: string;
    isUpgraded: boolean;
  };

  export type NodeTypeConfigStruct = {
    minETHStake: BigNumberish;
    minDPNStake: BigNumberish;
    baseRewardRate: BigNumberish;
    maxCapacity: BigNumberish;
    isActive: boolean;
  };

  export type NodeTypeConfigStructOutput = [
    minETHStake: bigint,
    minDPNStake: bigint,
    baseRewardRate: bigint,
    maxCapacity: bigint,
    isActive: boolean
  ] & {
    minETHStake: bigint;
    minDPNStake: bigint;
    baseRewardRate: bigint;
    maxCapacity: bigint;
    isActive: boolean;
  };
}

export interface NodeRightsNFTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PERFORMANCE_DECIMALS"
      | "SLASHING_COOLDOWN"
      | "approve"
      | "balanceOf"
      | "bridgeToChain"
      | "crossChainBridges"
      | "dpnTokenContract"
      | "emergencyWithdraw"
      | "getApproved"
      | "getNodeDetails"
      | "getNodeTypeStats"
      | "getOwnerNodes"
      | "isApprovedForAll"
      | "lastPerformanceUpdate"
      | "mintNodeRights"
      | "name"
      | "nodeCapacityUsed"
      | "nodeRights"
      | "nodeTypeConfigs"
      | "owner"
      | "ownerNodes"
      | "ownerOf"
      | "participationContract"
      | "renounceOwnership"
      | "rewardCalculatorContract"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setDPNTokenContract"
      | "setParticipationContract"
      | "supportsInterface"
      | "symbol"
      | "tokenByIndex"
      | "tokenOfOwnerByIndex"
      | "tokenURI"
      | "totalSupply"
      | "transferFrom"
      | "transferOwnership"
      | "updateNodeTypeConfig"
      | "updatePerformance"
      | "upgradeNode"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "CrossChainBridge"
      | "NodeRightsMinted"
      | "NodeSlashed"
      | "NodeUpgraded"
      | "OwnershipTransferred"
      | "PerformanceUpdated"
      | "RewardsDistributed"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PERFORMANCE_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLASHING_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeToChain",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "crossChainBridges",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dpnTokenContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeTypeStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerNodes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPerformanceUpdate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintNodeRights",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nodeCapacityUsed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nodeRights",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nodeTypeConfigs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerNodes",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "participationContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardCalculatorContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDPNTokenContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setParticipationContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateNodeTypeConfig",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePerformance",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeNode",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "PERFORMANCE_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLASHING_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bridgeToChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "crossChainBridges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dpnTokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeTypeStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerNodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPerformanceUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintNodeRights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nodeCapacityUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nodeRights", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nodeTypeConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerNodes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardCalculatorContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDPNTokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setParticipationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateNodeTypeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePerformance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeNode",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainBridgeEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    destinationChain: string,
    operator: AddressLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    destinationChain: string,
    operator: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    destinationChain: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeRightsMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    owner: AddressLike,
    nodeType: BigNumberish,
    ethStaked: BigNumberish,
    dpnStaked: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    owner: string,
    nodeType: bigint,
    ethStaked: bigint,
    dpnStaked: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    owner: string;
    nodeType: bigint;
    ethStaked: bigint;
    dpnStaked: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeSlashedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    newStatus: BigNumberish,
    penaltyAmount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    newStatus: bigint,
    penaltyAmount: bigint,
    reason: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    newStatus: bigint;
    penaltyAmount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeUpgradedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    additionalETH: BigNumberish,
    additionalDPN: BigNumberish,
    newPerformanceScore: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    additionalETH: bigint,
    additionalDPN: bigint,
    newPerformanceScore: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    additionalETH: bigint;
    additionalDPN: bigint;
    newPerformanceScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PerformanceUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    newScore: BigNumberish,
    uptimeAdded: BigNumberish,
    status: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    newScore: bigint,
    uptimeAdded: bigint,
    status: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    newScore: bigint;
    uptimeAdded: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDistributedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    rewardAmount: BigNumberish,
    performanceBonus: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    rewardAmount: bigint,
    performanceBonus: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    rewardAmount: bigint;
    performanceBonus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NodeRightsNFT extends BaseContract {
  connect(runner?: ContractRunner | null): NodeRightsNFT;
  waitForDeployment(): Promise<this>;

  interface: NodeRightsNFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PERFORMANCE_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  SLASHING_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  bridgeToChain: TypedContractMethod<
    [tokenId: BigNumberish, destinationChain: string],
    [void],
    "nonpayable"
  >;

  crossChainBridges: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  dpnTokenContract: TypedContractMethod<[], [string], "view">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getNodeDetails: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [
        NodeRightsNFT.NodeRightsStructOutput,
        NodeRightsNFT.NodeTypeConfigStructOutput,
        bigint,
        bigint
      ] & {
        node: NodeRightsNFT.NodeRightsStructOutput;
        config: NodeRightsNFT.NodeTypeConfigStructOutput;
        timeStaked: bigint;
        estimatedRewards: bigint;
      }
    ],
    "view"
  >;

  getNodeTypeStats: TypedContractMethod<
    [nodeType: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        totalNodes: bigint;
        totalStakedETH: bigint;
        averagePerformance: bigint;
        activeNodes: bigint;
      }
    ],
    "view"
  >;

  getOwnerNodes: TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  lastPerformanceUpdate: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  mintNodeRights: TypedContractMethod<
    [nodeType: BigNumberish, dpnStakeAmount: BigNumberish, metadata: string],
    [void],
    "payable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  nodeCapacityUsed: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  nodeRights: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        nodeType: bigint;
        stakedETH: bigint;
        stakedDPN: bigint;
        mintedAt: bigint;
        lastRewardClaim: bigint;
        status: bigint;
        totalUptime: bigint;
        performanceScore: bigint;
        metadata: string;
        isUpgraded: boolean;
      }
    ],
    "view"
  >;

  nodeTypeConfigs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        minETHStake: bigint;
        minDPNStake: bigint;
        baseRewardRate: bigint;
        maxCapacity: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  ownerNodes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  participationContract: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardCalculatorContract: TypedContractMethod<[], [string], "view">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setDPNTokenContract: TypedContractMethod<
    [_dpnToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setParticipationContract: TypedContractMethod<
    [_participation: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenByIndex: TypedContractMethod<[index: BigNumberish], [bigint], "view">;

  tokenOfOwnerByIndex: TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateNodeTypeConfig: TypedContractMethod<
    [
      nodeType: BigNumberish,
      minETHStake: BigNumberish,
      minDPNStake: BigNumberish,
      baseRewardRate: BigNumberish,
      isActive: boolean
    ],
    [void],
    "nonpayable"
  >;

  updatePerformance: TypedContractMethod<
    [
      tokenId: BigNumberish,
      uptimeSeconds: BigNumberish,
      performanceScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  upgradeNode: TypedContractMethod<
    [tokenId: BigNumberish, additionalDPN: BigNumberish],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PERFORMANCE_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLASHING_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "bridgeToChain"
  ): TypedContractMethod<
    [tokenId: BigNumberish, destinationChain: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "crossChainBridges"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "dpnTokenContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getNodeDetails"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [
        NodeRightsNFT.NodeRightsStructOutput,
        NodeRightsNFT.NodeTypeConfigStructOutput,
        bigint,
        bigint
      ] & {
        node: NodeRightsNFT.NodeRightsStructOutput;
        config: NodeRightsNFT.NodeTypeConfigStructOutput;
        timeStaked: bigint;
        estimatedRewards: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNodeTypeStats"
  ): TypedContractMethod<
    [nodeType: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        totalNodes: bigint;
        totalStakedETH: bigint;
        averagePerformance: bigint;
        activeNodes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnerNodes"
  ): TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastPerformanceUpdate"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintNodeRights"
  ): TypedContractMethod<
    [nodeType: BigNumberish, dpnStakeAmount: BigNumberish, metadata: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nodeCapacityUsed"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "nodeRights"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        nodeType: bigint;
        stakedETH: bigint;
        stakedDPN: bigint;
        mintedAt: bigint;
        lastRewardClaim: bigint;
        status: bigint;
        totalUptime: bigint;
        performanceScore: bigint;
        metadata: string;
        isUpgraded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nodeTypeConfigs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        minETHStake: bigint;
        minDPNStake: bigint;
        baseRewardRate: bigint;
        maxCapacity: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerNodes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "participationContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardCalculatorContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDPNTokenContract"
  ): TypedContractMethod<[_dpnToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setParticipationContract"
  ): TypedContractMethod<[_participation: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenByIndex"
  ): TypedContractMethod<[index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenOfOwnerByIndex"
  ): TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateNodeTypeConfig"
  ): TypedContractMethod<
    [
      nodeType: BigNumberish,
      minETHStake: BigNumberish,
      minDPNStake: BigNumberish,
      baseRewardRate: BigNumberish,
      isActive: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePerformance"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      uptimeSeconds: BigNumberish,
      performanceScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeNode"
  ): TypedContractMethod<
    [tokenId: BigNumberish, additionalDPN: BigNumberish],
    [void],
    "payable"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainBridge"
  ): TypedContractEvent<
    CrossChainBridgeEvent.InputTuple,
    CrossChainBridgeEvent.OutputTuple,
    CrossChainBridgeEvent.OutputObject
  >;
  getEvent(
    key: "NodeRightsMinted"
  ): TypedContractEvent<
    NodeRightsMintedEvent.InputTuple,
    NodeRightsMintedEvent.OutputTuple,
    NodeRightsMintedEvent.OutputObject
  >;
  getEvent(
    key: "NodeSlashed"
  ): TypedContractEvent<
    NodeSlashedEvent.InputTuple,
    NodeSlashedEvent.OutputTuple,
    NodeSlashedEvent.OutputObject
  >;
  getEvent(
    key: "NodeUpgraded"
  ): TypedContractEvent<
    NodeUpgradedEvent.InputTuple,
    NodeUpgradedEvent.OutputTuple,
    NodeUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PerformanceUpdated"
  ): TypedContractEvent<
    PerformanceUpdatedEvent.InputTuple,
    PerformanceUpdatedEvent.OutputTuple,
    PerformanceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDistributed"
  ): TypedContractEvent<
    RewardsDistributedEvent.InputTuple,
    RewardsDistributedEvent.OutputTuple,
    RewardsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "CrossChainBridge(uint256,string,address)": TypedContractEvent<
      CrossChainBridgeEvent.InputTuple,
      CrossChainBridgeEvent.OutputTuple,
      CrossChainBridgeEvent.OutputObject
    >;
    CrossChainBridge: TypedContractEvent<
      CrossChainBridgeEvent.InputTuple,
      CrossChainBridgeEvent.OutputTuple,
      CrossChainBridgeEvent.OutputObject
    >;

    "NodeRightsMinted(uint256,address,uint8,uint256,uint256)": TypedContractEvent<
      NodeRightsMintedEvent.InputTuple,
      NodeRightsMintedEvent.OutputTuple,
      NodeRightsMintedEvent.OutputObject
    >;
    NodeRightsMinted: TypedContractEvent<
      NodeRightsMintedEvent.InputTuple,
      NodeRightsMintedEvent.OutputTuple,
      NodeRightsMintedEvent.OutputObject
    >;

    "NodeSlashed(uint256,uint8,uint256,string)": TypedContractEvent<
      NodeSlashedEvent.InputTuple,
      NodeSlashedEvent.OutputTuple,
      NodeSlashedEvent.OutputObject
    >;
    NodeSlashed: TypedContractEvent<
      NodeSlashedEvent.InputTuple,
      NodeSlashedEvent.OutputTuple,
      NodeSlashedEvent.OutputObject
    >;

    "NodeUpgraded(uint256,uint256,uint256,uint256)": TypedContractEvent<
      NodeUpgradedEvent.InputTuple,
      NodeUpgradedEvent.OutputTuple,
      NodeUpgradedEvent.OutputObject
    >;
    NodeUpgraded: TypedContractEvent<
      NodeUpgradedEvent.InputTuple,
      NodeUpgradedEvent.OutputTuple,
      NodeUpgradedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PerformanceUpdated(uint256,uint256,uint256,uint8)": TypedContractEvent<
      PerformanceUpdatedEvent.InputTuple,
      PerformanceUpdatedEvent.OutputTuple,
      PerformanceUpdatedEvent.OutputObject
    >;
    PerformanceUpdated: TypedContractEvent<
      PerformanceUpdatedEvent.InputTuple,
      PerformanceUpdatedEvent.OutputTuple,
      PerformanceUpdatedEvent.OutputObject
    >;

    "RewardsDistributed(uint256,uint256,uint256)": TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;
    RewardsDistributed: TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
