/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ParticipationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimReward"
      | "nextId"
      | "nodeStakes"
      | "nodes"
      | "recordUptime"
      | "registerNode"
      | "stakeToNode"
      | "stats"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "NodeRegistered"
      | "RewardClaimed"
      | "StakeUpdated"
      | "UptimeRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nextId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nodeStakes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nodes", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "recordUptime",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerNode",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeToNode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stats", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nodeStakes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nodes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordUptime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeToNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stats", data: BytesLike): Result;
}

export namespace NodeRegisteredEvent {
  export type InputTuple = [
    nodeId: BigNumberish,
    owner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [nodeId: bigint, owner: string, timestamp: bigint];
  export interface OutputObject {
    nodeId: bigint;
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    nodeId: BigNumberish,
    owner: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    nodeId: bigint,
    owner: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    nodeId: bigint;
    owner: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeUpdatedEvent {
  export type InputTuple = [
    nodeId: BigNumberish,
    staker: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    nodeId: bigint,
    staker: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    nodeId: bigint;
    staker: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UptimeRecordedEvent {
  export type InputTuple = [
    nodeId: BigNumberish,
    minutesUp: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    nodeId: bigint,
    minutesUp: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    nodeId: bigint;
    minutesUp: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Participation extends BaseContract {
  connect(runner?: ContractRunner | null): Participation;
  waitForDeployment(): Promise<this>;

  interface: ParticipationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimReward: TypedContractMethod<
    [nodeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextId: TypedContractMethod<[], [bigint], "view">;

  nodeStakes: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  nodes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        owner: string;
        metadata: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  recordUptime: TypedContractMethod<
    [nodeId: BigNumberish, minutesUp: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerNode: TypedContractMethod<[metadata: string], [void], "nonpayable">;

  stakeToNode: TypedContractMethod<[nodeId: BigNumberish], [void], "payable">;

  stats: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        uptime: bigint;
        lastUpdate: bigint;
        earned: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[nodeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nodeStakes"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "nodes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        owner: string;
        metadata: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordUptime"
  ): TypedContractMethod<
    [nodeId: BigNumberish, minutesUp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerNode"
  ): TypedContractMethod<[metadata: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeToNode"
  ): TypedContractMethod<[nodeId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "stats"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        uptime: bigint;
        lastUpdate: bigint;
        earned: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "NodeRegistered"
  ): TypedContractEvent<
    NodeRegisteredEvent.InputTuple,
    NodeRegisteredEvent.OutputTuple,
    NodeRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "StakeUpdated"
  ): TypedContractEvent<
    StakeUpdatedEvent.InputTuple,
    StakeUpdatedEvent.OutputTuple,
    StakeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UptimeRecorded"
  ): TypedContractEvent<
    UptimeRecordedEvent.InputTuple,
    UptimeRecordedEvent.OutputTuple,
    UptimeRecordedEvent.OutputObject
  >;

  filters: {
    "NodeRegistered(uint256,address,uint256)": TypedContractEvent<
      NodeRegisteredEvent.InputTuple,
      NodeRegisteredEvent.OutputTuple,
      NodeRegisteredEvent.OutputObject
    >;
    NodeRegistered: TypedContractEvent<
      NodeRegisteredEvent.InputTuple,
      NodeRegisteredEvent.OutputTuple,
      NodeRegisteredEvent.OutputObject
    >;

    "RewardClaimed(uint256,address,uint256,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "StakeUpdated(uint256,address,uint256,uint256)": TypedContractEvent<
      StakeUpdatedEvent.InputTuple,
      StakeUpdatedEvent.OutputTuple,
      StakeUpdatedEvent.OutputObject
    >;
    StakeUpdated: TypedContractEvent<
      StakeUpdatedEvent.InputTuple,
      StakeUpdatedEvent.OutputTuple,
      StakeUpdatedEvent.OutputObject
    >;

    "UptimeRecorded(uint256,uint256,uint256)": TypedContractEvent<
      UptimeRecordedEvent.InputTuple,
      UptimeRecordedEvent.OutputTuple,
      UptimeRecordedEvent.OutputObject
    >;
    UptimeRecorded: TypedContractEvent<
      UptimeRecordedEvent.InputTuple,
      UptimeRecordedEvent.OutputTuple,
      UptimeRecordedEvent.OutputObject
    >;
  };
}
