/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace StakingPool {
  export type PoolConfigStruct = {
    minStake: BigNumberish;
    tierMultiplier: BigNumberish;
    baseRewardRate: BigNumberish;
    totalStaked: BigNumberish;
    totalShares: BigNumberish;
    isActive: boolean;
  };

  export type PoolConfigStructOutput = [
    minStake: bigint,
    tierMultiplier: bigint,
    baseRewardRate: bigint,
    totalStaked: bigint,
    totalShares: bigint,
    isActive: boolean
  ] & {
    minStake: bigint;
    tierMultiplier: bigint;
    baseRewardRate: bigint;
    totalStaked: bigint;
    totalShares: bigint;
    isActive: boolean;
  };

  export type StakePositionStruct = {
    tier: BigNumberish;
    lockPeriod: BigNumberish;
    amount: BigNumberish;
    shares: BigNumberish;
    stakedAt: BigNumberish;
    unlocksAt: BigNumberish;
    lastRewardClaim: BigNumberish;
    isActive: boolean;
  };

  export type StakePositionStructOutput = [
    tier: bigint,
    lockPeriod: bigint,
    amount: bigint,
    shares: bigint,
    stakedAt: bigint,
    unlocksAt: bigint,
    lastRewardClaim: bigint,
    isActive: boolean
  ] & {
    tier: bigint;
    lockPeriod: bigint;
    amount: bigint;
    shares: bigint;
    stakedAt: bigint;
    unlocksAt: bigint;
    lastRewardClaim: bigint;
    isActive: boolean;
  };
}

export interface StakingPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "SECONDS_PER_DAY"
      | "claimAllRewards"
      | "claimRewards"
      | "dpnTokenContract"
      | "emergencyWithdraw"
      | "emergencyWithdrawEnabled"
      | "enableEmergencyWithdraw"
      | "getGlobalStats"
      | "getPoolStats"
      | "getPositionDetails"
      | "getUserPositions"
      | "lockConfigs"
      | "nodeRightsContract"
      | "owner"
      | "poolConfigs"
      | "renounceOwnership"
      | "setDPNTokenContract"
      | "setNodeRightsContract"
      | "stakeToPool"
      | "totalRewardsDistributed"
      | "totalValueLocked"
      | "transferOwnership"
      | "updateLockConfig"
      | "updatePoolConfig"
      | "userPositionCount"
      | "userPositions"
      | "withdrawStake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyWithdraw"
      | "OwnershipTransferred"
      | "PoolConfigUpdated"
      | "PoolStaked"
      | "RewardsClaimed"
      | "StakeWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SECONDS_PER_DAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimAllRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dpnTokenContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enableEmergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionDetails",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockConfigs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nodeRightsContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolConfigs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDPNTokenContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setNodeRightsContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeToPool",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRewardsDistributed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalValueLocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLockConfig",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePoolConfig",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "userPositionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userPositions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStake",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SECONDS_PER_DAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAllRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dpnTokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableEmergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nodeRightsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDPNTokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNodeRightsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeToPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRewardsDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalValueLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLockConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePoolConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPositionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStake",
    data: BytesLike
  ): Result;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolConfigUpdatedEvent {
  export type InputTuple = [
    tier: BigNumberish,
    minStake: BigNumberish,
    tierMultiplier: BigNumberish,
    baseRewardRate: BigNumberish
  ];
  export type OutputTuple = [
    tier: bigint,
    minStake: bigint,
    tierMultiplier: bigint,
    baseRewardRate: bigint
  ];
  export interface OutputObject {
    tier: bigint;
    minStake: bigint;
    tierMultiplier: bigint;
    baseRewardRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolStakedEvent {
  export type InputTuple = [
    user: AddressLike,
    positionId: BigNumberish,
    tier: BigNumberish,
    lockPeriod: BigNumberish,
    amount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    positionId: bigint,
    tier: bigint,
    lockPeriod: bigint,
    amount: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    user: string;
    positionId: bigint;
    tier: bigint;
    lockPeriod: bigint;
    amount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    positionId: BigNumberish,
    rewardAmount: BigNumberish,
    totalClaimed: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    positionId: bigint,
    rewardAmount: bigint,
    totalClaimed: bigint
  ];
  export interface OutputObject {
    user: string;
    positionId: bigint;
    rewardAmount: bigint;
    totalClaimed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeWithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    positionId: BigNumberish,
    amount: BigNumberish,
    penalty: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    positionId: bigint,
    amount: bigint,
    penalty: bigint
  ];
  export interface OutputObject {
    user: string;
    positionId: bigint;
    amount: bigint;
    penalty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StakingPool extends BaseContract {
  connect(runner?: ContractRunner | null): StakingPool;
  waitForDeployment(): Promise<this>;

  interface: StakingPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  SECONDS_PER_DAY: TypedContractMethod<[], [bigint], "view">;

  claimAllRewards: TypedContractMethod<[], [void], "nonpayable">;

  claimRewards: TypedContractMethod<
    [positionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  dpnTokenContract: TypedContractMethod<[], [string], "view">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  emergencyWithdrawEnabled: TypedContractMethod<[], [bigint], "view">;

  enableEmergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  getGlobalStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, [bigint, bigint, bigint, bigint]] & {
        tvl: bigint;
        totalRewards: bigint;
        totalStakers: bigint;
        poolDistribution: [bigint, bigint, bigint, bigint];
      }
    ],
    "view"
  >;

  getPoolStats: TypedContractMethod<
    [tier: BigNumberish],
    [
      [StakingPool.PoolConfigStructOutput, bigint, bigint, bigint] & {
        config: StakingPool.PoolConfigStructOutput;
        activeStakers: bigint;
        averageStake: bigint;
        poolUtilization: bigint;
      }
    ],
    "view"
  >;

  getPositionDetails: TypedContractMethod<
    [user: AddressLike, positionId: BigNumberish],
    [
      [StakingPool.StakePositionStructOutput, bigint, bigint, boolean] & {
        position: StakingPool.StakePositionStructOutput;
        pendingRewards: bigint;
        timeToUnlock: bigint;
        canWithdraw: boolean;
      }
    ],
    "view"
  >;

  getUserPositions: TypedContractMethod<
    [user: AddressLike],
    [StakingPool.StakePositionStructOutput[]],
    "view"
  >;

  lockConfigs: TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint] & { lockDays: bigint; timeMultiplier: bigint }],
    "view"
  >;

  nodeRightsContract: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  poolConfigs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        minStake: bigint;
        tierMultiplier: bigint;
        baseRewardRate: bigint;
        totalStaked: bigint;
        totalShares: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDPNTokenContract: TypedContractMethod<
    [_dpnToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setNodeRightsContract: TypedContractMethod<
    [_nodeRights: AddressLike],
    [void],
    "nonpayable"
  >;

  stakeToPool: TypedContractMethod<
    [tier: BigNumberish, lockPeriod: BigNumberish],
    [void],
    "payable"
  >;

  totalRewardsDistributed: TypedContractMethod<[], [bigint], "view">;

  totalValueLocked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateLockConfig: TypedContractMethod<
    [
      lockPeriod: BigNumberish,
      lockDays: BigNumberish,
      timeMultiplier: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updatePoolConfig: TypedContractMethod<
    [
      tier: BigNumberish,
      minStake: BigNumberish,
      tierMultiplier: BigNumberish,
      baseRewardRate: BigNumberish,
      isActive: boolean
    ],
    [void],
    "nonpayable"
  >;

  userPositionCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userPositions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        tier: bigint;
        lockPeriod: bigint;
        amount: bigint;
        shares: bigint;
        stakedAt: bigint;
        unlocksAt: bigint;
        lastRewardClaim: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  withdrawStake: TypedContractMethod<
    [positionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SECONDS_PER_DAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimAllRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[positionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dpnTokenContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdrawEnabled"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "enableEmergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getGlobalStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, [bigint, bigint, bigint, bigint]] & {
        tvl: bigint;
        totalRewards: bigint;
        totalStakers: bigint;
        poolDistribution: [bigint, bigint, bigint, bigint];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolStats"
  ): TypedContractMethod<
    [tier: BigNumberish],
    [
      [StakingPool.PoolConfigStructOutput, bigint, bigint, bigint] & {
        config: StakingPool.PoolConfigStructOutput;
        activeStakers: bigint;
        averageStake: bigint;
        poolUtilization: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPositionDetails"
  ): TypedContractMethod<
    [user: AddressLike, positionId: BigNumberish],
    [
      [StakingPool.StakePositionStructOutput, bigint, bigint, boolean] & {
        position: StakingPool.StakePositionStructOutput;
        pendingRewards: bigint;
        timeToUnlock: bigint;
        canWithdraw: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPositions"
  ): TypedContractMethod<
    [user: AddressLike],
    [StakingPool.StakePositionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockConfigs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint] & { lockDays: bigint; timeMultiplier: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "nodeRightsContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolConfigs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        minStake: bigint;
        tierMultiplier: bigint;
        baseRewardRate: bigint;
        totalStaked: bigint;
        totalShares: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDPNTokenContract"
  ): TypedContractMethod<[_dpnToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setNodeRightsContract"
  ): TypedContractMethod<[_nodeRights: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeToPool"
  ): TypedContractMethod<
    [tier: BigNumberish, lockPeriod: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "totalRewardsDistributed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalValueLocked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLockConfig"
  ): TypedContractMethod<
    [
      lockPeriod: BigNumberish,
      lockDays: BigNumberish,
      timeMultiplier: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePoolConfig"
  ): TypedContractMethod<
    [
      tier: BigNumberish,
      minStake: BigNumberish,
      tierMultiplier: BigNumberish,
      baseRewardRate: BigNumberish,
      isActive: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userPositionCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userPositions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        tier: bigint;
        lockPeriod: bigint;
        amount: bigint;
        shares: bigint;
        stakedAt: bigint;
        unlocksAt: bigint;
        lastRewardClaim: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawStake"
  ): TypedContractMethod<[positionId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolConfigUpdated"
  ): TypedContractEvent<
    PoolConfigUpdatedEvent.InputTuple,
    PoolConfigUpdatedEvent.OutputTuple,
    PoolConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolStaked"
  ): TypedContractEvent<
    PoolStakedEvent.InputTuple,
    PoolStakedEvent.OutputTuple,
    PoolStakedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "StakeWithdrawn"
  ): TypedContractEvent<
    StakeWithdrawnEvent.InputTuple,
    StakeWithdrawnEvent.OutputTuple,
    StakeWithdrawnEvent.OutputObject
  >;

  filters: {
    "EmergencyWithdraw(address,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolConfigUpdated(uint8,uint256,uint256,uint256)": TypedContractEvent<
      PoolConfigUpdatedEvent.InputTuple,
      PoolConfigUpdatedEvent.OutputTuple,
      PoolConfigUpdatedEvent.OutputObject
    >;
    PoolConfigUpdated: TypedContractEvent<
      PoolConfigUpdatedEvent.InputTuple,
      PoolConfigUpdatedEvent.OutputTuple,
      PoolConfigUpdatedEvent.OutputObject
    >;

    "PoolStaked(address,uint256,uint8,uint8,uint256,uint256)": TypedContractEvent<
      PoolStakedEvent.InputTuple,
      PoolStakedEvent.OutputTuple,
      PoolStakedEvent.OutputObject
    >;
    PoolStaked: TypedContractEvent<
      PoolStakedEvent.InputTuple,
      PoolStakedEvent.OutputTuple,
      PoolStakedEvent.OutputObject
    >;

    "RewardsClaimed(address,uint256,uint256,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "StakeWithdrawn(address,uint256,uint256,uint256)": TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;
    StakeWithdrawn: TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;
  };
}
